In [1]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
!wget https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta/+build/15331130/+files/google-drive-ocamlfuse_0.7.0-0ubuntu1_amd64.deb
!dpkg -i google-drive-ocamlfuse_0.7.0-0ubuntu1_amd64.deb
!apt-get install -f
!apt-get -y install -qq fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

E: Package 'python-software-properties' has no installation candidate
Selecting previously unselected package google-drive-ocamlfuse.
(Reading database ... 131304 files and directories currently installed.)
Preparing to unpack .../google-drive-ocamlfuse_0.7.3-0ubuntu3~ubuntu18.04.1_amd64.deb ...
Unpacking google-drive-ocamlfuse (0.7.3-0ubuntu3~ubuntu18.04.1) ...
Setting up google-drive-ocamlfuse (0.7.3-0ubuntu3~ubuntu18.04.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
--2019-04-15 01:22:02--  https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta/+build/15331130/+files/google-drive-ocamlfuse_0.7.0-0ubuntu1_amd64.deb
Resolving launchpad.net (launchpad.net)... 91.189.89.222, 91.189.89.223, 2001:67c:1560:8003::8004, ...
Connecting to launchpad.net (launchpad.net)|91.189.89.222|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-04-15 01:22:02 ERROR 404: Not Found.

dpkg: error: cannot access archive 'google-drive-ocaml

In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

In [3]:
!pip install torch

In [0]:
import torch

In [5]:
print(torch.__version__)

1.0.1.post2


In [8]:
##  Tensors
x = torch.empty(5,3)
print(x)

tensor([[7.9117e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 1.9926e-01],
        [3.3236e-09, 3.2772e-09, 2.1121e+20],
        [8.4275e-07, 6.5197e-10, 2.0890e+20],
        [1.3605e+22, 4.3203e-05, 4.3053e-01]])


In [7]:
x = torch.rand(5,3)
print(x)

tensor([[0.4047, 0.2796, 0.6215],
        [0.0686, 0.7075, 0.1993],
        [0.4897, 0.5818, 0.5803],
        [0.6934, 0.8618, 0.3292],
        [0.6729, 0.5844, 0.4305]])


In [11]:
x = torch.rand(3)
x

tensor([0.0671, 0.7329, 0.6420])

In [12]:
x = torch.zeros(5,3,dtype=torch.float32)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
x = torch.tensor([5.5,3,6.32])
x

tensor([5.5000, 3.0000, 6.3200])

In [14]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [15]:
x = torch.rand_like(x,dtype=torch.float)
x

tensor([[0.8117, 0.5934, 0.9660],
        [0.7371, 0.2624, 0.5655],
        [0.7597, 0.3565, 0.3074],
        [0.6424, 0.3629, 0.5440],
        [0.8328, 0.6663, 0.2899]])

In [16]:
x.size()

torch.Size([5, 3])

In [17]:
y = torch.rand(5,3)
y

tensor([[0.6025, 0.2403, 0.4100],
        [0.2910, 0.9097, 0.7725],
        [0.8375, 0.0883, 0.6224],
        [0.9140, 0.1207, 0.3042],
        [0.0058, 0.1442, 0.5394]])

In [18]:
x + y

tensor([[1.4142, 0.8337, 1.3760],
        [1.0281, 1.1721, 1.3379],
        [1.5972, 0.4448, 0.9298],
        [1.5564, 0.4836, 0.8482],
        [0.8386, 0.8104, 0.8293]])

In [20]:
torch.add(x,y)

tensor([[1.4142, 0.8337, 1.3760],
        [1.0281, 1.1721, 1.3379],
        [1.5972, 0.4448, 0.9298],
        [1.5564, 0.4836, 0.8482],
        [0.8386, 0.8104, 0.8293]])

In [21]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[1.4142, 0.8337, 1.3760],
        [1.0281, 1.1721, 1.3379],
        [1.5972, 0.4448, 0.9298],
        [1.5564, 0.4836, 0.8482],
        [0.8386, 0.8104, 0.8293]])

In [23]:
print(y.add_(x))
print(x)
print(x.add_(y))
print(y)

tensor([[3.6401, 2.2609, 3.7181],
        [2.7933, 2.6066, 3.2414],
        [3.9541, 1.2461, 2.1671],
        [3.7552, 1.3300, 2.2405],
        [2.5100, 2.2871, 1.9485]])
tensor([[2.2259, 1.4271, 2.3421],
        [1.7652, 1.4345, 1.9034],
        [2.3569, 0.8013, 1.2372],
        [2.1988, 0.8465, 1.3923],
        [1.6714, 1.4767, 1.1192]])
tensor([[5.8660, 3.6880, 6.0601],
        [4.5585, 4.0411, 5.1448],
        [6.3111, 2.0473, 3.4043],
        [5.9539, 2.1765, 3.6328],
        [4.1814, 3.7637, 3.0678]])
tensor([[3.6401, 2.2609, 3.7181],
        [2.7933, 2.6066, 3.2414],
        [3.9541, 1.2461, 2.1671],
        [3.7552, 1.3300, 2.2405],
        [2.5100, 2.2871, 1.9485]])


In [24]:
print(x[:,1])
print(x[1,:])

tensor([3.6880, 4.0411, 2.0473, 2.1765, 3.7637])
tensor([4.5585, 4.0411, 5.1448])


In [26]:
a = torch.rand(4,3)
b = a.view(12)
c = a.view(-1,6)
d = a.view(-1,4)
print(a.size(),b.size(),c.size(),d.size())

torch.Size([4, 3]) torch.Size([12]) torch.Size([2, 6]) torch.Size([3, 4])


In [28]:
e = torch.rand(1)
print(e)
print(e.item())

tensor([0.3681])
0.36805713176727295


In [29]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [30]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [31]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [32]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [33]:
torch.cuda.is_available()

True